apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: assisted-events-stream-e1fd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: assisted-events-stream-e1fd
    app.kubernetes.io/part-of: assisted-events-stream
  name: assisted-events-stream-e1fd
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: assisted-events-stream-e1fd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: assisted-events-stream-e1fd
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/assisted-installer-tenant/assisted-events-stream/assisted-events-stream-e1fd@sha256:589c1d28ca88e781180a672ec37635cb2a1504a9bdf14486e08e63fcd8429b36
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
